name: Deploy Azure SignalR Private Endpoint
on:
  push:
    branches:
      - master
    paths:
      - 'DevOps/**'
      - '.github/workflows/azure-deployment.yml'
  workflow_dispatch:

env:
  TERRAFORM_FILENAME: 'infrastructure.tfstate'
  TERRAFORM_WORKING_DIRECTORY: './DevOps/Terraform/Infrastructures'
  TERRAFORM_STORAGE_ACCOUNT: 'tfstateexampleazfunc'
  TERRAFORM_CONTAINER_NAME: 'tfstatecontainer'
  TERRAFORM_RESOURCE_GROUP_NAME: 'RG-Example'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

  setup-infrastructure-on-test:
    runs-on: windows-latest
    environment: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/terraform@main
        id: run-terraform
        with:
          working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
          environment: 'test'
          arm-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          arm-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          arm-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          terraform-resource-group-name: ${{ env.TERRAFORM_RESOURCE_GROUP_NAME }}
          terraform-storage-account: ${{ env.TERRAFORM_STORAGE_ACCOUNT }}
          terraform-container-name: ${{ env.TERRAFORM_CONTAINER_NAME }}
          terraform-filename: 'test.${{ env.TERRAFORM_FILENAME }}'